In [1]:
import os

import cv2
import numpy as np



In [32]:

# 创建两个数组
a = np.array([[1, 2], [3, 4],[5, 6],[7, 8]])
b = np.array([9,10,11,12,13])
print(a.shape)
print(b.shape)

(4, 2)
(5,)


In [33]:
signle_features = np.concatenate((a, np.tile(b, (4, 1))), axis=1)
print(signle_features)


[[ 1  2  9 10 11 12 13]
 [ 3  4  9 10 11 12 13]
 [ 5  6  9 10 11 12 13]
 [ 7  8  9 10 11 12 13]]


In [16]:
y = [1] * 5 + [0] * 6
print(y)

[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]


In [21]:
with open('C:/Users/younger/Pictures/ApplePic/photo_tag/useful/00000-0-AGJI0864.txt') as file:
    lines = file.read().splitlines()
    for line in lines:
        words = line.split(',')
        print(words,"\n")

['blurry', ' blurry_background', ' blurry_foreground', ' depth_of_field', ' photo_\\(medium\\)', ' cosplay_photo', ' motion_blur', ' looking_at_viewer', ' school_uniform', ' photo_background', ' skirt', ' jacket', ' blonde_hair', ' bowtie', ' bow', ' 1girl', ' long_hair', ' kneehighs', ' outstretched_hand', ' white_legwear', ' grey_skirt'] 



In [24]:
import numpy as np
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from keras.applications.vgg16 import VGG16

# 加载 VGG16 模型
model = VGG16(weights='imagenet')

# 加载图片并将其转换为四维张量
img_path = 'C:/Users/younger/Pictures/ApplePic/photo_tag/useful/00000-0-AGJI0864.png'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

# 使用 VGG16 模型进行预测
preds = model.predict(x)

Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/keras-applications/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels.h5: None -- [WinError 10054] 远程主机强迫关闭了一个现有的连接。

In [28]:
img=cv2.imread('C:/Users/younger/Pictures/ApplePic/photo_tag/useful/00000-0-AGJI0864.png', cv2.IMREAD_IGNORE_ORIENTATION)
model = VGG16(weights='imagenet', include_top=False)
# 预处理图像
img = cv2.resize(img, (512,512))
img = np.expand_dims(img, axis=0)
img = preprocess_input(img)
print(img)
# 提取特征向量
img_features = model.predict(img)
img_features = img_features.flatten()

[[[-19.939003 -29.779    -35.68     ...  82.        82.        81.      ]
  [-16.939003 -29.779    -33.68     ...  82.        82.        82.      ]
  [-17.939003 -27.779    -32.68     ...  83.        84.        82.      ]
  ...
  [-27.939003 -39.779    -43.68     ...  65.        64.        64.      ]
  [-25.939003 -36.779    -43.68     ...  65.        66.        66.      ]
  [-23.939003 -36.779    -42.68     ...  66.        65.        65.      ]]]


ValueError: in user code:

    File "c:\Users\younger\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "c:\Users\younger\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\younger\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "c:\Users\younger\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\training.py", line 2111, in predict_step
        return self(x, training=False)
    File "c:\Users\younger\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\younger\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\engine\input_spec.py", line 253, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'vgg16' (type Functional).
    
    Input 0 of layer "block1_conv1" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (None, 512, 512)
    
    Call arguments received by layer 'vgg16' (type Functional):
      • inputs=tf.Tensor(shape=(None, 512, 512), dtype=float32)
      • training=False
      • mask=None
